-- DML: DATA MANIPULATION LANGUAGUE 

-- RECUPERA DADOS DO BANCO DE DADOS
select * from senso where

-- INSERI DADOS EM MA TABELA
insert

-- ATUALIZA OS DADOS NUMA tabela
UPDATE

-- EXCLUI OS REGISTROS DE UMA TABELA 
DELETE
